name: SLSA Go releaser

on:
  workflow_dispatch:
  release:
    types: [created]

permissions: read-all

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@f7dd8c54c2067bafc12ca7a55595d5ee9b75204a  # v2.1.0
    with:
      go-version-file: go.mod
      upload-assets: false
